#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KellySelden.Libraries.Mvc.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Player.cshtml"
    using KellySelden.Libraries.Mvc.Infrastructure;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Player.cshtml"
    using KellySelden.Libraries.Mvc.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Player.cshtml")]
    public partial class Player : System.Web.Mvc.WebViewPage<PlayerModel>
    {
        public Player()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\Player.cshtml"
  
    Html.QueueEmbeddedScript(KellySeldenLinks.Scripts.flowplayer_3_2_6_min_js);
    Html.QueueEmbeddedScript(KellySeldenLinks.Scripts.Player_js);
    Html.QueueEmbeddedStyle(KellySeldenLinks.Content.Player_css);

	string id = Guid.NewGuid().ToString();
	string href = null, style = null, src = null;
    if (Model.Type != PlayerType.YouTube)
    {
        href = Model.FilePath;
    }
    if (Model.Type == PlayerType.Video)
    {
        style = string.Format("background-image: url({0});", Model.SplashPath);
        src = Html.GetWebResourceUrl(KellySeldenLinks.flowplayer.play_large_png);
    }
    style += string.Format("height: {0}px; width: {1}px;", Model.Height, Model.Width);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 829), Tuple.Create("\"", 837)
            
            #line 25 "..\..\Views\Shared\Player.cshtml"
, Tuple.Create(Tuple.Create("", 834), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 834), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 838), Tuple.Create("\"", 891)
            
            #line 25 "..\..\Views\Shared\Player.cshtml"
, Tuple.Create(Tuple.Create("", 846), Tuple.Create<System.Object, System.Int32>(KellySeldenMVC.Shared.Views.ViewNames.Player
            
            #line default
            #line hidden
, 846), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 892), Tuple.Create("\"", 904)
            
            #line 25 "..\..\Views\Shared\Player.cshtml"
, Tuple.Create(Tuple.Create("", 899), Tuple.Create<System.Object, System.Int32>(href
            
            #line default
            #line hidden
, 899), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 905), Tuple.Create("\"", 919)
            
            #line 25 "..\..\Views\Shared\Player.cshtml"
         , Tuple.Create(Tuple.Create("", 913), Tuple.Create<System.Object, System.Int32>(style
            
            #line default
            #line hidden
, 913), false)
);

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Shared\Player.cshtml"
	
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\Player.cshtml"
  if (src != null)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<img");

WriteAttribute("src", Tuple.Create(" src=\"", 953), Tuple.Create("\"", 963)
            
            #line 28 "..\..\Views\Shared\Player.cshtml"
, Tuple.Create(Tuple.Create("", 959), Tuple.Create<System.Object, System.Int32>(src
            
            #line default
            #line hidden
, 959), false)
);

WriteLiteral(" />\r\n");

            
            #line 29 "..\..\Views\Shared\Player.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    Player(\'");

            
            #line 32 "..\..\Views\Shared\Player.cshtml"
       Write(id);

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 32 "..\..\Views\Shared\Player.cshtml"
              Write(Model.Type);

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 32 "..\..\Views\Shared\Player.cshtml"
                             Write(Model.FilePath);

            
            #line default
            #line hidden
WriteLiteral("\')\r\n</script>");

        }
    }
}
#pragma warning restore 1591
